In [ ]:
'''
REFERENCES
1. https://thispointer.com/how-to-save-numpy-array-to-a-csv-file-using-numpy-savetxt-in-python/
2. https://stackoverflow.com/questions/54361557/appending-to-file-using-savetxt/54361619
3. https://www.kaggle.com/pierrek20/multiclass-iris-prediction-with-tensorflow-keras
'''

In [3]:
!python getSamples.py

=> loaded pretrained model from 'data/vibe_data/spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/InputData/input_test_set/warrior2/File8.mp4 -f image2 -v error /tmp/File8_mp4/%06d.png"
Images saved to "/tmp/File8_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:08<00:00,  1.29it/s]
Finished. Detection + Tracking FPS 12.09
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.35s/it]
VIBE FPS: 42.54
Total time spent: 11.48 seconds (including model loading time).
Total FPS (including model loading time): 8.71.
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/InputData/input_test_set/warrior2/File3.mp4 -f image2 -v error /tmp/File3_mp4/%06d.png"
Images saved to "/tmp/File3_mp4"
Input video num

100%|█████████████████████████████████████████████| 9/9 [00:05<00:00,  1.79it/s]
Finished. Detection + Tracking FPS 17.22
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.63s/it]
VIBE FPS: 61.27
Total time spent: 8.25 seconds (including model loading time).
Total FPS (including model loading time): 12.13.
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/InputData/input_test_set/childs/File5.mp4 -f image2 -v error /tmp/File5_mp4/%06d.png"
Images saved to "/tmp/File5_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:09<00:00,  1.12it/s]
Finished. Detection + Tracking FPS 10.84
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:03<00:00,  3.92s/it]
VIBE FPS: 25.50
Total time spent: 13.96 seconds (including model loading time).
Total FPS (including model loading time): 7.16.
Running "ffmpeg -i /home/ubuntu/PoseEst

Images saved to "/tmp/File179_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:06<00:00,  1.71it/s]
Finished. Detection + Tracking FPS 16.63
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.84s/it]
VIBE FPS: 54.29
Total time spent: 8.66 seconds (including model loading time).
Total FPS (including model loading time): 11.54.
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/InputData/input_test_set/mountain/File171.mp4 -f image2 -v error /tmp/File171_mp4/%06d.png"
Images saved to "/tmp/File171_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:05<00:00,  1.74it/s]
Finished. Detection + Tracking FPS 16.83
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
VIBE FPS: 56.28
Total time spent: 8.52 seconds (including mode

Images saved to "/tmp/File178_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:06<00:00,  1.71it/s]
Finished. Detection + Tracking FPS 16.56
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.83s/it]
VIBE FPS: 54.61
Total time spent: 8.68 seconds (including model loading time).
Total FPS (including model loading time): 11.52.
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/InputData/input_test_set/mountain/File161.mp4 -f image2 -v error /tmp/File161_mp4/%06d.png"
Images saved to "/tmp/File161_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:05<00:00,  1.77it/s]
Finished. Detection + Tracking FPS 17.08
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.74s/it]
VIBE FPS: 57.46
Total time spent: 8.42 seconds (including mode

100%|█████████████████████████████████████████████| 9/9 [00:06<00:00,  1.66it/s]
Finished. Detection + Tracking FPS 16.27
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.85s/it]
VIBE FPS: 54.12
Total time spent: 8.82 seconds (including model loading time).
Total FPS (including model loading time): 11.34.
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/InputData/input_test_set/tree/File1.mp4 -f image2 -v error /tmp/File1_mp4/%06d.png"
Images saved to "/tmp/File1_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:06<00:00,  1.66it/s]
Finished. Detection + Tracking FPS 15.98
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.65s/it]
VIBE FPS: 60.56
Total time spent: 8.73 seconds (including model loading time).
Total FPS (including model loading time): 11.45.
Running "ffmpeg -i /home/ubuntu/PoseEstim

Images saved to "/tmp/File10_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:05<00:00,  1.87it/s]
Finished. Detection + Tracking FPS 18.21
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.59s/it]
VIBE FPS: 62.96
Total time spent: 7.90 seconds (including model loading time).
Total FPS (including model loading time): 12.66.
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/InputData/input_test_set/seatedforwardbend/File8.mp4 -f image2 -v error /tmp/File8_mp4/%06d.png"
Images saved to "/tmp/File8_mp4"
Input video number of frames 100
Running Multi-Person-Tracker
100%|█████████████████████████████████████████████| 9/9 [00:06<00:00,  1.51it/s]
Finished. Detection + Tracking FPS 14.70
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:02<00:00,  2.12s/it]
VIBE FPS: 47.10
Total time spent: 9.72 seconds (including mo

In [46]:
import pandas as pd
input_data = pd.read_csv('output_joints3d.csv', header=None, sep=' ')
print(input_data.shape)
input_data = input_data.round(3)
input_data.drop_duplicates(inplace=True)
input_data.shape

(8499, 148)


(6986, 148)

In [47]:
X, y = input_data.iloc[:, :-1], input_data.iloc[:, [-1]]
X.shape

(6986, 147)

In [10]:
y

147
0      10
1      10
2      10
3      10
4      10
...   ...
8494    6
8495    6
8496    6
8497    6
8498    6

[8499 rows x 1 columns]

In [39]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(y)

/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [7]:
from sklearn.model_selection import train_test_split


In [40]:
dummy_y

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, dummy_y, random_state = 0, stratify=y, test_size=0.2) 

In [29]:
y_train[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [9]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.utils import to_categorical

In [42]:
model = Sequential()
model.add(Dense(8, input_dim = X_train.shape[1] , activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(11, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'] )

model.fit(X_train, y_train, epochs = 3, batch_size = 2)

Epoch 1/10
5588/5588 [==============================] - 4s 742us/step - loss: 0.6070 - accuracy: 0.8014
Epoch 2/10
5588/5588 [==============================] - 4s 700us/step - loss: 0.0159 - accuracy: 0.9987
Epoch 3/10
5588/5588 [==============================] - 4s 712us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 4/10
5588/5588 [==============================] - 4s 699us/step - loss: 0.0143 - accuracy: 0.9966
Epoch 5/10
5588/5588 [==============================] - 4s 704us/step - loss: 2.9254e-04 - accuracy: 1.0000
Epoch 6/10
5588/5588 [==============================] - 4s 701us/step - loss: 9.5989e-05 - accuracy: 1.0000
Epoch 7/10
5588/5588 [==============================] - 4s 701us/step - loss: 3.1824e-05 - accuracy: 1.0000
Epoch 8/10
5588/5588 [==============================] - 4s 703us/step - loss: 8.8643e-06 - accuracy: 1.0000
Epoch 9/10
5588/5588 [==============================] - 4s 701us/step - loss: 2.2065e-06 - accuracy: 1.0000
Epoch 10/10
5588/5588 [=====================

In [43]:
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

1398/1398 [==============================] - 0s 66us/step

accuracy: 100.00%


In [44]:
scores1 = model.evaluate(X_train, y_train)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores1[1]*100))

5588/5588 [==============================] - 0s 21us/step

accuracy: 100.00%


In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 1184      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                90        
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_4 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_5 (Dense)              (None, 11)                121       
Total params: 1,615
Trainable params: 1,615
Non-trainable params: 0
_________________________________________________________________


In [14]:
model_test = Sequential()
model_test.add(Dense(8, input_dim=X_train.shape[1], activation='relu'))
model_test.add(Dense(11, activation='softmax'))
# Compile model
model_test.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_test.fit(X_train, y_train, epochs = 10, batch_size = 2)

Epoch 1/10
6799/6799 [==============================] - 4s 547us/step - loss: 0.7638 - accuracy: 0.8373
Epoch 2/10
6799/6799 [==============================] - 4s 530us/step - loss: 0.0665 - accuracy: 0.9779
Epoch 3/10
6799/6799 [==============================] - 4s 528us/step - loss: 0.0196 - accuracy: 0.9984
Epoch 4/10
6799/6799 [==============================] - 4s 527us/step - loss: 0.0079 - accuracy: 1.0000
Epoch 5/10
6799/6799 [==============================] - 4s 529us/step - loss: 0.0038 - accuracy: 1.0000
Epoch 6/10
6799/6799 [==============================] - 4s 528us/step - loss: 0.0018 - accuracy: 1.0000
Epoch 7/10
6799/6799 [==============================] - 4s 526us/step - loss: 8.4485e-04 - accuracy: 1.0000
Epoch 8/10
6799/6799 [==============================] - 4s 523us/step - loss: 4.0220e-04 - accuracy: 1.0000
Epoch 9/10
6799/6799 [==============================] - 4s 527us/step - loss: 1.8648e-04 - accuracy: 1.0000
Epoch 10/10
6799/6799 [=============================

In [28]:
scores_test = model_test.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model_test.metrics_names[1], scores_test[1]*100))
scores_test_1 = model_test.evaluate(X_train, y_train)
print("\n%s: %.2f%%" % (model_test.metrics_names[1], scores_test_1[1]*100))

1700/1700 [==============================] - 0s 46us/step

accuracy: 100.00%
6799/6799 [==============================] - 0s 20us/step

accuracy: 100.00%


In [38]:
output_temp = model_test.predict_classes(X_test)
output_temp

array([3, 4, 1, ..., 4, 3, 2])

In [40]:
y_test[1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [55]:
test_data = pd.read_csv('output_joints3d_single.csv', header=None, sep=' ')
x_temp_data, y_temp_data = test_data.iloc[:, :-1], test_data.iloc[:, [-1]]
model_test.predict_classes(x_temp_data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [58]:
X_train

0         1         2         3         4         5         6    \
1917 -0.035697 -0.851714 -0.196293 -0.015349 -0.724806 -0.040755 -0.179616   
2212  0.011460 -0.896477 -0.115452  0.008332 -0.756037  0.033017 -0.168268   
1216 -0.486851 -0.020590  0.154596 -0.448396 -0.213317  0.190402 -0.361771   
3037 -0.009750 -0.807142 -0.191917  0.000107 -0.701628 -0.025819 -0.159009   
3883 -0.005031 -0.860567 -0.156830  0.002721 -0.730585 -0.003067 -0.164921   
...        ...       ...       ...       ...       ...       ...       ...   
4373  0.020187 -0.886137  0.029763 -0.000949 -0.713633  0.131289 -0.127897   
7891  0.190424 -0.690156  0.242935  0.105991 -0.644734  0.082025  0.220647   
4859 -0.340858  0.243547  0.065478 -0.412746  0.051905  0.052075 -0.385773   
3264 -0.009012 -0.862263 -0.184795 -0.002667 -0.733699 -0.029284 -0.170840   
2732  0.007012 -0.873730 -0.075414 -0.001336 -0.730852  0.064163 -0.163624   

           7         8         9    ...       137       138       139  \
1917 -0.616065 -0.007025 -0.230592  ... -0.163820 -0.064446 -0.886384   
2212 -0.655233  0.039951 -0.229983  ... -0.075993 -0.020160 -0.929701   
1216 -0.186043  0.325173 -0.510603  ...  0.149565 -0.512190 -0.034871   
3037 -0.594779  0.001338 -0.181285  ... -0.165701 -0.037161 -0.850089   
3883 -0.623987  0.012994 -0.225232  ... -0.122207 -0.035232 -0.896080   
...        ...       ...       ...  ...       ...       ...       ...   
4373 -0.697277  0.078616 -0.139662  ...  0.083886 -0.017589 -0.899266   
7891 -0.530287  0.019281  0.296944  ...  0.235413  0.220930 -0.727866   
4859  0.026754  0.221283 -0.527407  ...  0.029842 -0.396769  0.240247   
3264 -0.624728 -0.001332 -0.218915  ... -0.149830 -0.039075 -0.898273   
2732 -0.651816  0.047573 -0.298267  ... -0.032640 -0.027808 -0.904114   

           140       141       142       143       144       145       146  
1917 -0.153090  0.053239 -0.866738 -0.080769 -0.085821 -0.858716 -0.057937  
2212 -0.072548  0.089121 -0.898608  0.010897 -0.054462 -0.896248  0.018618  
1216  0.209179 -0.564178 -0.151920  0.137712 -0.496813 -0.121476  0.277431  
3037 -0.156604  0.074341 -0.835851 -0.080019 -0.059507 -0.839617 -0.060957  
3883 -0.115170  0.077140 -0.873253 -0.036609 -0.061985 -0.868889 -0.021587  
...        ...       ...       ...       ...       ...       ...       ...  
4373  0.078085  0.080372 -0.831956  0.153550 -0.062616 -0.831223  0.144136  
7891  0.207852  0.097307 -0.761263  0.168517  0.216323 -0.731028  0.108495  
4859  0.098707 -0.450204  0.165928 -0.024894 -0.456456  0.150261  0.142213  
3264 -0.143658  0.072811 -0.874181 -0.063249 -0.068535 -0.871803 -0.049701  
2732 -0.034588  0.074165 -0.869612  0.054185 -0.066060 -0.865449  0.051415  

[6799 rows x 147 columns]

In [18]:
!python generateSingleVideo.py

=> loaded pretrained model from 'data/vibe_data/spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running "ffmpeg -i /home/ubuntu/PoseEstimation/VIBE/DogVideo.mp4 -f image2 -v error /tmp/DogVideo_mp4/%06d.png"
Images saved to "/tmp/DogVideo_mp4"
Input video number of frames 272
Running Multi-Person-Tracker
100%|███████████████████████████████████████████| 23/23 [00:24<00:00,  1.07it/s]
Finished. Detection + Tracking FPS 11.21
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.59s/it]
VIBE FPS: 35.84
Total time spent: 32.71 seconds (including model loading time).
Total FPS (including model loading time): 8.31.


In [26]:
test_data_new = pd.read_csv('output_joints3d_dog.csv', header=None, sep=' ')
x_temp_new, y_temp_new = test_data_new.iloc[:, :-1], test_data_new.iloc[:, [-1]]
model.predict_classes(x_temp_new)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [27]:
test_data_new = pd.read_csv('output_joints3d_plank.csv', header=None, sep=' ')
x_temp_new, y_temp_new = test_data_new.iloc[:, :-1], test_data_new.iloc[:, [-1]]
model.predict_classes(x_temp_new)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [32]:
new_test_df = pd.read_csv('/home/ubuntu/PoseEstimation/VIBE/OutputData/train_output_joints3d.csv', header=None, sep=' ')
new_test_df

0         1         2         3         4         5         6    \
0     -0.067365 -0.841839 -0.277034 -0.066560 -0.744217 -0.095676 -0.237887   
1     -0.066804 -0.838090 -0.276292 -0.065783 -0.743840 -0.093549 -0.236406   
2     -0.071513 -0.835238 -0.275110 -0.067524 -0.743250 -0.091508 -0.236445   
3     -0.074013 -0.834658 -0.273729 -0.068007 -0.742925 -0.090150 -0.235991   
4     -0.075496 -0.834307 -0.272843 -0.068332 -0.742578 -0.089336 -0.235720   
...         ...       ...       ...       ...       ...       ...       ...   
66693 -0.055209  0.050918 -0.607116 -0.049467 -0.073377 -0.443465 -0.221364   
66694 -0.054836  0.050994 -0.606901 -0.049099 -0.073520 -0.443506 -0.220912   
66695 -0.054669  0.050964 -0.606823 -0.049046 -0.073528 -0.443422 -0.220914   
66696 -0.054915  0.050827 -0.607071 -0.049216 -0.073510 -0.443481 -0.221128   
66697 -0.054718  0.050828 -0.606902 -0.049003 -0.073710 -0.443545 -0.220806   

            7         8         9    ...       138       139       140  \
0     -0.680133 -0.040026 -0.466865  ... -0.098003 -0.882884 -0.240226   
1     -0.680317 -0.036085 -0.463347  ... -0.097192 -0.880066 -0.240425   
2     -0.680360 -0.031975 -0.461186  ... -0.101402 -0.877672 -0.239381   
3     -0.680870 -0.029764 -0.459809  ... -0.103399 -0.877173 -0.237681   
4     -0.681148 -0.028435 -0.458896  ... -0.104595 -0.876814 -0.236558   
...         ...       ...       ...  ...       ...       ...       ...   
66693 -0.131380 -0.356843 -0.433109  ... -0.086711 -0.001198 -0.625078   
66694 -0.131557 -0.357003 -0.432393  ... -0.086219 -0.001124 -0.625023   
66695 -0.131388 -0.356959 -0.432647  ... -0.086100 -0.001126 -0.624929   
66696 -0.131465 -0.356893 -0.432762  ... -0.086408 -0.001277 -0.625070   
66697 -0.131719 -0.357042 -0.432212  ... -0.086105 -0.001279 -0.625047   

            141       142       143       144       145       146  147  
0      0.013323 -0.864786 -0.152407 -0.135449 -0.866718 -0.141739   10  
1      0.014179 -0.863576 -0.152486 -0.134390 -0.866332 -0.141480   10  
2      0.011256 -0.862558 -0.153088 -0.136844 -0.865256 -0.139726   10  
3      0.010199 -0.861870 -0.152789 -0.137545 -0.864845 -0.137626   10  
4      0.009530 -0.861242 -0.152473 -0.138005 -0.864373 -0.136294   10  
...         ...       ...       ...       ...       ...       ...  ...  
66693  0.027590 -0.069556 -0.571006 -0.121104 -0.081776 -0.563900    6  
66694  0.028082 -0.069372 -0.570962 -0.120509 -0.081860 -0.564082    6  
66695  0.028137 -0.069469 -0.570850 -0.120470 -0.081810 -0.563969    6  
66696  0.027870 -0.069649 -0.571003 -0.120805 -0.081880 -0.563948    6  
66697  0.028180 -0.069550 -0.571004 -0.120401 -0.082027 -0.564138    6  

[66698 rows x 148 columns]

In [48]:
X_new_test, y_new_test = new_test_df.iloc[:, :-1], new_test_df.iloc[:, [-1]]
encoded_Y = encoder.transform(y_new_test)
# convert integers to dummy variables (i.e. one hot encoded)
test_new_y = np_utils.to_categorical(y_new_test)

/home/ubuntu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [49]:
scores_test_new = model.evaluate(X_new_test, test_new_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores_test_new[1]*100))

66698/66698 [==============================] - 1s 21us/step

accuracy: 75.78%


In [52]:
import pickle
fileName = "mymodel.pkl"
pickle.dump(model, open(fileName, 'wb'))
 
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(fileName, 'rb'))
result = loaded_model.evaluate(X_new_test, test_new_y)
print(result[1]*100)

66698/66698 [==============================] - 2s 26us/step
75.78188180923462
